/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package automan;

import automan.handlers.GarageHandler;
import automan.handlers.MessageHandler;
import org.tinylog.Logger;

import java.io.InputStream;
import java.io.PrintStream;
import java.util.Random;

public class AutomanEngine {

    public static void main(String[] args) {
        Logger.info("Starting...");

        InputStream in = System.in;
        PrintStream out = System.out;

        out.println("Welcome to Automan!");
        try {
            MessageHandler messageHandler = new MessageHandler(out);

            Core core = new Core(out,
                    in,
                    new GarageHandler(new Random(), messageHandler),
                    messageHandler);
            core.run();
        } catch (Exception e) {
            out.println("Unexpected error.");
            Logger.error(e, "Failure caught by engine");
        }

        out.println("Automan shutting down. See ya!");

        shutdownSequence();
    }


    private static void shutdownSequence() {
        Logger.info("Stopping...");
    }
}
